### ISSUE TITLE
Train classification val acc is very LOW !!

### ISSUE THREAD

**Issue by Hansoluo** [see--/kuzushiji-recognition#1]
Hi, Thank you for sharing you code. 

I used your code to train a model, found the classification was  very bad. My submission score was 0.00. There is something I missed.  I'm trying to get it right.  

And I found in the training , validation classification acc is very low. The training acc curve is below.

![](https://www.googleapis.com/download/storage/v1/b/kaggle-user-content/o/inbox%2F1527136%2F1918d3c49eca8b77fba5eb566efe62c3%2F12_val_acc.png?generation=1589355399205111&alt=media)

The model you released, the `val_classes_acc` is also only 0.4986. This confused me.  Why the validation classes acc is very low, but you can get a test F1_score 0.910 ?

Thanks!!

**Comment by see--** [comment]
Hey, you seem to be quite confused :P

My recommendation is: Try to get the inference running first (`submit.py`). Use the weights that I provided. If you can reproduce the submission results (~0.94 F1 on Kaggle), you can try reproducing the training. Regarding the accuracy: There are >4200 classes, ~50% accuracy seems fine. Imagenet has 1000 classes and 76% accuracy (Resnet-50).

One more hint. Use `vis_submission.py` to visualize your predictions. Do the predictions look good? If you get a 0.0 score, your submission is wrongly formatted.

Good luck!

**Comment by Hansoluo** [comment]
@see--  Thanks for your replying. I suceess reproduced the submission results with your weights. But I still have the problem.  

There are three images below, the left one plot with the groudtruth labels, the middle one plot with your predictions, and the the right one plot with my predictions. 

![12_val_vis_gt](https://user-images.githubusercontent.com/21060177/81910224-3b755b00-95fe-11ea-9c0f-d9701082b20e.png)

You can see my predictions of centers looks well, but the predictions of classification is really bad. 

I checked my submission format, it's ok. I think maybe there are some reasons caused that:
1. the predication of classification was really bad, something wrong with the training of classification
2. somthing wrong happened in label convert processing: `int_to_label`
3. somthing wrong happened in classification inference

**Comment by see--** [comment]
Nice visualization! I think the class mapping is off (i.e. 2.). For example in the last row, 3rd and 2nd last letters, the model predicts the same letters, which is good. Try to double check that the mapping is correct.

**Comment by Hansoluo** [comment]
Thanks!! I fixed the bug. Your observations are keen.The mapping is not correct. 

I forget a `set` is an unordered data structure. So, The train and infernce proceess will return diffrent `label_to_int` dict.

```python
	def _covert_label(self, df):
		length = 5
		labels = []
		for label in df["labels"]:
			split_label = label.split()[::length]
			labels += split_label
		labels = set(labels)
                # There is a bug !!!
                # label_to_int = {v: k for k, v in enumerate(labels)}
		label_to_int = {v: k for k, v in enumerate(sorted(list(labels)))}
        return label_to_int
```

Thank you very much!!!
